source "https://code.aliyun.com/mpaas-public/podspecs.git"
use_frameworks!

platform :ios, '10.0'

target 'HYCivicCenter_Example' do
  
  pod 'HYCivicCenter', :path => '../'
  
  pod 'AFNetworking'
  pod 'AlipaySDK-iOS'
  pod 'Masonry'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'WechatOpenSDK'
  pod 'SDWebImage'
  pod 'SVProgressHUD'
  pod 'TZImagePickerController', '~> 3.8.3'
#  pod 'AntVerify', '1.0.0.220608162853'

  target 'HYCivicCenter_Tests' do
    inherit! :search_paths

  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end


