# Uncomment the next line to define a global platform for your project
#source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'
source "https://code.aliyun.com/mpaas-public/podspecs.git"
use_modular_headers!
use_frameworks!

platform :ios, '11.0'

target 'HYCivicCenter_Example' do
  
  pod 'HYCivicCenter', :path => '../'
  
  pod 'AFNetworking'
  pod 'AlipaySDK-iOS'
  pod 'AntVerify'
  pod 'Masonry'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'WechatOpenSDK'
  pod 'SDWebImage'
  pod 'SVProgressHUD'
  pod 'TZImagePickerController', '~> 3.8.3'

  target 'HYCivicCenter_Tests' do
    inherit! :search_paths

  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end


